import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FirstPage from './components/FirstPage'
import Footer from './components/Footer'
import Infosection from './components/Infosection'
import Navbar from './components/Navbar/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
    <Head>
      <title>Webflow: Create a custom website</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/son.ico" />
    </Head>
    <Navbar/>
    <FirstPage/>
    <Infosection/>
    <Footer/>
    
    
      
    </div>
  )
}
